export default {
    subnavigation: {
        type: 'Subnavigation',
        items: [{
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }, {
            type: 'SubNavigationItem',
            label: 'Ultimaker PLA',
            url: 'http://nu.nl',
            image: {
                type: 'Cimage',
                url: 'https://images.ctfassets.net/yadj1kx9rmg0/wtrHxeu3zEoEce2MokCSi/cf6f68efdcf625fdc060607df0f3baef/quwowooybuqbl6ntboz3.jpg',
                alt: 'An example image',
                quality: 65,
                radius: 0,
                imageFormat: 'png',
                resizeBehavior: 'fill',
                focusArea: 'center',
                backgroundColor: null,
                mimeType: 'png',
            },
        }],
    },
};
